## Figura 4.8 - Diversidad alfa de eucariotas por nivel taxonomico (Img/cap3/Alpha_Eukarya.png)
source("/home/camila/GIT/Tesis_Maestria/Analisis_Comparativo/Fresa_Solena/_paleta_tesis.R")
source("/home/camila/GIT/Tesis_Maestria/Analisis_Comparativo/Fresa_Solena/_alfa_por_nivel.R")
datos <- cargar_fresa()
euk <- subset_taxa(datos$fil, Kingdom == "Eukaryota")
fig <- figura_alfa_niveles(euk)
guardar_figura("Alpha_Eukarya.png", fig, out_cap3, ancho = 30, alto = 19)
